# Generated by Django 5.2.8 on 2026-08-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('topic', models.CharField(choices=[('individual', 'Individual Tax Filing'), ('business', 'Small Business Tax'), ('planning', 'Tax Planning'), ('other', 'Other')], default='other', max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
