# Generated by Django 5.2.8 on 2026-08-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='topic',
            field=models.CharField(choices=[('general', 'General Tax Advisory'), ('itr', 'Income Tax Return (ITR)'), ('gst', 'GST Registration / Filing'), ('business', 'Business Incorporation'), ('audit', 'Tax Audit & Accounting')], default='general', max_length=20),
        ),
    ]
